### ISSUE TITLE
Add SCIM2 provisioning feature

### ISSUE THREAD

**Issue by kesavany** [wso2-extensions/identity-outbound-provisioning-scim#25]
**Description:**
Add SCIM2 provisioning feature to SCIM provisioning connector.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madurangasiriwardena** [comment]
Closing this issue since it is tracked in the product-is repo.
